export const ProjectsItems = [
	{
		title: "Altar",
		date: "Jul 2025",
		desc: "Created a microblogging app with real-time features, user profiles, and bookmarks using Supabase.",
		stack: "TypeScript, NextJS, Convex",
		icon: "/logo/altar_logo.svg",
		href: "https://thealtar.vercel.app/",
		images: ["/landing/altar/homepage.webp", "/landing/altar/profile.webp", "/landing/altar/settings.webp"],
	},
	{
		title: "Flower GAN",
		date: "May 2025",
		desc: "Trained a DCGAN to generate realistic 64×64 flower images, improving FID from 92 to 43.",
		stack: "Python, PyTorch",
		icon: "/logo/flower_gan_logo.svg",
		href: "https://www.kaggle.com/code/ashishk1331/flower-gan",
		images: [
			"/landing/flower-gan/flower-gan.gif",
			"/landing/flower-gan/flower-gan-result.webp",
			"/landing/flower-gan/flower-gan-loss.webp",
		],
	},
	{
		title: "Wingman - VLMs for Android",
		date: "Mar 2025",
		desc: "Made a mobile app to run vision-language models locally with Llama.cpp and FastAPI.",
		stack: "React Native, FastAPI, Llama.cpp",
		icon: "/logo/wingman_logo.svg",
		href: "https://github.com/ashishk1331/smolnlm-android",
		images: [
			"/landing/wingman/login.webp",
			"/landing/wingman/scan.webp",
			"/landing/wingman/inference.webp",
			"/landing/wingman/vlm.webp",
		],
	},
	{
		title: "80 Cereals Dataset",
		date: "Jan 2025",
		desc: "Performed EDA and trained regressors on cereal data achieving R² ≈ 0.99.",
		stack: "Python, Sklearn, Seaborn",
		icon: "/logo/80_cereal_logo.svg",
		href: "https://www.kaggle.com/code/ashishk1331/80-cereals",
		images: [
			"/landing/80-cereals/cereal.webp",
			"/landing/80-cereals/heatmap.webp",
			"/landing/80-cereals/rating-v-calories.webp",
			"/landing/80-cereals/xgboost-residplot.webp",
		],
	},
	{
		title: "folder-routing",
		date: "Dec 2023",
		desc: "Built a lightweight ExpressJS wrapper with Next.js-style routing and async middleware.",
		stack: "JavaScript, ExpressJS",
		icon: "/logo/folder_routing_logo.svg",
		href: "https://github.com/ashishk1331/folder-routing",
		images: ["/landing/folder-routing-banner.webp"],
	},
	{
		title: "Tetrapack",
		date: "Jun 2023",
		desc: "Developed a Notion-style JavaScript parser with isolated block rendering and fast bundling.",
		stack: "JavaScript, ESBuild, Storybook",
		icon: "/logo/tetrapack_logo.svg",
		href: "https://tetra-docs.vercel.app/",
		images: [
			"/landing/tetrapack/tetrapack-banner.webp",
			"/landing/tetrapack/process.webp",
			"/landing/tetrapack/tetra-paper.webp",
			"/landing/tetrapack/carbon.webp",
		],
	},
];
